In [ ]:
import pandas as pd

data = pd.read_csv('/content/output_2001.csv')

data.head()

,First-level discipline,Second-level disciplines,ICCS_2001_10.txt,ICCS_2001_100.txt,ICCS_2001_101.txt,ICCS_2001_102.txt,ICCS_2001_104.txt,ICCS_2001_105.txt,ICCS_2001_106.txt,ICCS_2001_108.txt,...,ICCS_2001_91.txt,ICCS_2001_92.txt,ICCS_2001_93.txt,ICCS_2001_94.txt,ICCS_2001_95.txt,ICCS_2001_96.txt,ICCS_2001_97.txt,ICCS_2001_98.txt,ICCS_2001_99.txt,Sum
0,"Computer hardware, system, engineering",Printed circuit board,0.029865,0.015441,0.028374,0.017987,0.038485,0.026408,0.017782,0.036902,...,0.033326,0.020702,0.025565,0.018401,0.037437,0.031302,0.021399,0.022367,0.018071,5.567942
1,"Computer hardware, system, engineering",Integrated circuit,0.012474,0.015240,0.041971,0.022223,0.035572,0.035518,0.020597,0.059607,...,0.026007,0.037328,0.026000,0.018435,0.038103,0.049187,0.033356,0.012466,0.016980,5.961214
2,"Computer hardware, system, engineering",Very-large-scale_integration,0.007768,0.009596,0.041011,0.014018,0.028776,0.034510,0.019790,0.049293,...,0.021542,0.032153,0.014077,0.017868,0.028765,0.028066,0.028394,0.008626,0.017331,4.860147
3,"Computer hardware, system, engineering",System on a chip,0.015128,0.022499,0.069637,0.026821,0.047891,0.064960,0.037307,0.066422,...,0.030218,0.066725,0.025578,0.017987,0.060023,0.045879,0.073811,0.023675,0.035144,8.323449
4,"Computer hardware, system, engineering",Green computing,0.021261,0.040599,0.060973,0.030407,0.054645,0.084765,0.032523,0.076066,...,0.022209,0.040041,0.062025,0.025608,0.066187,0.044297,0.041755,0.032797,0.031665,8.798078

In [ ]:
import json

with open('/content/data.json', 'r') as file:
    data = json.load(file)

print(data)

{'ICCS_2001_10.txt': ' Discrete Local Fairing of B-Spline Surfaces� Seok-Yong Hong, Chung-Seong Hong, Hyun-Chan Lee, and Koohyun Park Department of Information and Industrial Engineering, Hong-Ik University, Sangsu-dong 72-1, Mapo-gu, Seoul, Republic of Korea (121-791) sy hong@orgio.net, pulnaeum@shinbiro.com, hclee@wow.hongik.ac.kr, khpark@wow.hongik.ac.kr', 'ICCS_2001_100.txt': ' Authentication Service Model Supporting Multiple Domains in Distributed Computing Kyung-Ah Chang, Byung-Rae Lee, Tai-Yun Kim Dept. of Computer Science & Engineering, Korea University, 1, 5-ga, Anam-dong, Sungbuk-ku, Seoul, 136-701, Korea {gypsy93, brlee, tykim}@netlab.korea.ac.kr', 'ICCS_2001_101.txt': ' The Problem of Time Scales in Computer Visualization Mark Burgin1 , Damon Liu2 , and Walter Karplus2 1', 'ICCS_2001_102.txt': ' Attractor Density Models with Application to Analyzing the Stability of Biological Neural Networks Christian Storm and Walter J. Freeman University of California at Berkeley, Graduate Group in Biophysics, 9 Wellman Court, Berkeley, CA USA 94720 raystorm@uclink4.berkeley.edu, wfreeman@socrates.berkeley.edu http://sulcus.berkeley.edu', 'ICCS_2001_104.txt': ' The DOE Parallel Climate Model (PCM): The Computational Highway and Backroads Thomas Bettge, Anthony Craig, Rodney James, Vincent Wayland, and Gary Strand National Center for Atmospheric Research, 1850 Table Mesa Drive, Boulder, Colorado 80303 (bettge, tcraig, rodney, wayland, strandwg) @ucar.edu', 'ICCS_2001_105.txt': ' DMEFS Web Portal: A METOC Application Avichal Mehra and Jim Corbin Integrated Data Systems Laboratory Engineering Research Center Mississippi State University Stennis Space Center MS 39529 Mehra@erc.msstate.edu', 'ICCS_2001_106.txt': ' Achieving Performance Portability with SKaMPI for High-Performance MPI Programs Ralf Reussner and Gunnar Hunzelmann Chair Computer Science for Engineering and Science Universität Karlsruhe (T.H.) Am Fasanengarten 5, D-76128 Karlsruhe, Germany. �reussner|gunnar�@ira.uka.de', 'ICCS_2001_107.txt': ' Generalized High-Level Synthesis of Wavelet-Based Digital Systems via Nonlinear I/O Data Space Transformations Dongming Peng and Mi Lu Electrical Engineering Department, Texas A&M University, College Station, TX77843, USA', 'ICCS_2001_108.txt': ' Influences on the Solution Process for Large, NumericIntensive Automotive Simulations Myron Ginsberg, Ph.D. HPC Research and Education Farmington Hills, Michigan 48335-1222 USA m.ginsberg@ieee.org', 'ICCS_2001_109.txt': ' Evolutionary Puzzles: An Introduction to Genome Rearrangement Mathieu Blanchette Department of Computer Science and Engineering Box 352350 University of Washington Seattle, WA 98195-2350 U.S.A. 206-543-5118 fax: 206-543-8331 blanchem@cs.washington.edu', 'ICCS_2001_11.txt': ' Solvable Map Method for Integrating Nonlinear Hamiltonian Systems Govindan Rangarajan and Minita Sachidanand Department of Mathematics Indian Institute of Science Bangalore 560 012, India rangaraj@math.iisc.ernet.in', 'ICCS_2001_110.txt': ' Solving Nonlinear Differential Equations by a Neural Network Method 1', 'ICCS_2001_111.txt': ' A Feynman-Kac Path-Integral Implementation for Poisson’s Equation Chi-Ok Hwang and Michael Mascagni Department of Computer Science, Florida State University, 203 Love Building Tallahassee, FL 32306-4530', 'ICCS_2001_112.txt': ' Quasi Analog Formal Neuron and Its Learning Algorithm Hardware Karen Nazaryan Division of Microelectronics and Biomedical Devices, State Engineering University of Armenia, 375009, Terian Str. 105, Yerevan, Armenia nakar@freenet.am', 'ICCS_2001_113.txt': ' The MultiMedia Maintenance Management (M4) System Rachel J. McCrindle Applied Software Engineering Research Group, Department of Computer Science, The University of Reading, Whiteknights, PO Box 225, Reading, Berkshire, RG6 6AY, UK Tel: +44 118 931 6536, Fax: +44 118 975 1994 r.j.mccrindle@reading.ac.uk', 'ICCS_2001_114.txt': ' On the Use of a Diﬀerentiated Finite Element Package for Sensitivity Analysis� Christian H. Bischof, H. Martin Bücker, Bruno Lang, Arno Rasch, and Jakob W. Risch Institute for Scientiﬁc Computing, Aachen University of Technology, D–52056 Aachen, Germany {bischof, buecker, lang, rasch, risch}@sc.rwth-aachen.de http://www.sc.rwth-aachen.de', 'ICCS_2001_116.txt': ' Large-Scale Simulation and Visualization in Medicine: Applications to Cardiology, Neuroscience, and Medical Imaging Chris Johnson Director, Scientiﬁc Computing and Imaging Institute School of Computing Merrill Engineering Building 50 South Campus Central Dr., Room 3490 University of Utah Salt Lake City, Utah 84112-9205 Phone: +1-(801)-585-1867 FAX: +1-(801)-585-6513 crj@cs.utah.edu', 'ICCS_2001_117.txt': ' Getting Good Value Facts, Values, and Goals in Computational Linguistics� Michael A. Gilbert Department of Philosophy, York University, Toronto, Canada Gilbert@YorkU.ca', 'ICCS_2001_119.txt': ' An Empirical Study of Multimedia Argumentation Nancy Green Department of Mathematical Sciences, University of North Carolina at Greensboro Greensboro, North Carolina 27402, USA nlgreen@uncg.edu', 'ICCS_2001_120.txt': ' Noise-Induced Signal Enhancement in Heterogeneous Neural Networks Michael J. Barber and Babette K. Dellen Institut für Theoretische Physik, Universität zu Köln, D-50937 Köln, Germany mjb@thp.uni-koeln.de bd@thp.uni-koeln.de', 'ICCS_2001_122.txt': ' Bayesian Parameter Estimation: A Monte Carlo Approach', 'ICCS_2001_123.txt': ' Analysis of the Argumentative Eﬀect of Evaluative Semantics in Natural Language Serge V. Gavenko Moscow State Linguistic University Usacheva St., 62-510, Moscow 119048 Russia serge.gavenko@mtu-net.ru', 'ICCS_2001_124.txt': ' Simulation-Visualization Complexes as Generic Exploration Environment Elena V. Zudilova Integration Technologies Department Corning Scientific Center 4 Birzhevaya Linia, St. Petersburg 199034, RUSSIA tel.: 7 (812) 3229525 fax: +7 (812) 3292061 http://www.corning.com e-mail: ZudilovaEV@corning.com', 'ICCS_2001_126.txt': ' The Javelin Integrated Flight Simulation 1', 'ICCS_2001_127.txt': ' Fiddle: A Flexible Distributed Debugging Architecture João Lourenço', 'ICCS_2001_128.txt': ' The Monitoring and Steering Environment Christian Glasner, Roland Hügl, Bernhard Reitinger, Dieter Kranzlmüller, and Jens Volkert GUP Linz, Johannes Kepler University Linz, Altenbergerstr. 69, A-4040 Linz, Austria/Europe, kranzlmueller@gup.uni-linz.ac.at, http://www.gup.uni-linz.ac.at/', 'ICCS_2001_129.txt': ' Modelling the Effect of Premium Changes on Motor Insurance Customer Retention Rates Using Neural Networks 1', 'ICCS_2001_13.txt': ' Performance and Stability Analysis of a Message Oriented Reliable Multicast for Distributed Virtual Environments in Java Gunther Stuer, Jan Broeckhove, and Frans Arickx Antwerp University Department of Mathematics and Computer Sciences Groenenborgerlaan 171, 2020 Antwerp, Belgium gstuer@ruca.ua.ac.be', 'ICCS_2001_130.txt': ' Protocols and Software for Exploiting Myrinet Clusters P. Geoﬀray1 , C. Pham, L. Prylli2 , B. Tourancheau3 , and R. Westrelin 1', 'ICCS_2001_131.txt': ' Performance Prediction for Parallel Local Weather Forecast Programs W. Joppich and H. Mierendorﬀ GMD – German National Research Center for Information Technology Institute for Algorithms and Scientiﬁc Computing (SCAI) Schloß Birlinghoven, 53754 Sankt Augustin, Germany', 'ICCS_2001_132.txt': ' Parallel Bridging Models and Their Impact on Algorithm Design� Friedhelm Meyer auf der Heide and Rolf Wanka Dept. of Mathematics and Computer Science and Heinz Nixdorf Institute, Paderborn University, 33095 Paderborn, Germany. Email: {fmadh|wanka}@upb.de', 'ICCS_2001_133.txt': ' Quantiﬁcation of Uncertainty for Numerical Simulations with Conﬁdence Intervals James Glimm Distinguished/Leading Professor Dept of Applied Mathematics and Statistics P-138A Math Tower University at Stony Brook Stony Brook, NY 11794-3600 Phone: +1-(516)-632-8355 FAX: +1-(516)-632-8490 glimm@ams.sunysb.edu', 'ICCS_2001_134.txt': ' Computational Models of Natural Language Argument Chris Reed1 and Floriana Grasso2 1 2', 'ICCS_2001_135.txt': ' Scalable Large Scale Process Modeling and Simulations in Liquid Composite Molding Ram Mohan� , Dale Shires, and Andrew Mark U. S. Army Research Laboratory † High Performance Computing Division Aberdeen Proving Ground, MD 21005', 'ICCS_2001_136.txt': ' Numerical Simulation of Quantum Distributions: Instability and Quantum Chaos G.Y. Kryuchkyan, H.H. Adamyan, and S.B. Manvelyan Institute for Physical Research, National Academy of Sciences, Ashtarak-2, 378410, Armenia Yerevan State University, Alex Manookyan 1, 375049, Yerevan, Armenia', 'ICCS_2001_137.txt': ' Exploratory Study of Scientiﬁc Visualization Techniques for Program Visualization Brian J. d’Auriol, Claudia V. Casas, Pramod Kumar Chikkappaiah, L. Susan Draper, Ammar J. Esper, Jorge López, Rajesh Molakaseema, Seetharami R. Seelam, René Saenz, Qian Wen, and Zhengjing Yang Department of Computer Science, The University of Texas at El Paso, El Paso, TX 79968, USA', 'ICCS_2001_138.txt': ' Component Object Based Single System Image Middleware for Metacomputer Implementation of Genetic Programming on Clusters 2', 'ICCS_2001_14.txt': ' Task Environments for the Dynamic Development of Behavior Derek Harter and Robert Kozma Department of Mathematical Sciences; University of Memphis Memphis, TN 38152 USA {dharter, rkozma}@memphis.edu http://www.psyc.memphis.edu/{∼harterd, ∼kozmar}', 'ICCS_2001_140.txt': ' Visualizing the Memory Access Behavior of Shared Memory Applications on NUMA Architectures Jie Tao� , Wolfgang Karl, and Martin Schulz LRR-TUM, Institut für Informatik, Technische Universität München, 80290 München, Germany E-mail: {tao,karlw,schulzm}@in.tum.de', 'ICCS_2001_141.txt': ' TRaDe: Data Race Detection for Java Mark Christiaens1 and Koen De Bosschere1 ELIS, Ghent University, Sint-Pietersnieuwstraat 41, 9000 Gent, Belgium, {mchristi,kdb}@elis.rug.ac.be', 'ICCS_2001_142.txt': ' On Dynamic Generalized Voronoi Diagrams in the Euclidean Metric M.L. Gavrilova and J. Rokne Department of Computer Science, University of Calgary Calgary, AB, Canada, T2N 1N4 {marina,rokne}@cpsc.ucalgary.ca', 'ICCS_2001_143.txt': ' Numerical Investigation of Quantum Chaos in the Problem of Multichannel Scattering in Three Body System A.V. Bogdanov, A.S. Gevorkyan, and A.A. Udalov Institute for High-Performance Computing and Data Bases P/O Box 71, 194291, St-Petersburg, Russia, bogdanov@hm.csa.ru, ashot@fn.csa.ru, udalov@fn.csa.ru.', 'ICCS_2001_144.txt': ' Argumentation in Explanations to Logical Problems Armin Fiedler and Helmut Horacek Universität des Saarlandes, FR Informatik, Postfach 15 11 50, D-66041 Saarbrücken, Germany {afiedler|horacek}@cs.uni-sb.de', 'ICCS_2001_145.txt': ' Load Balancing for the Electronic Structure Program GREMLIN in a Very Heterogenous SSH-Connected WAN-Cluster of UNIX-Type Hosts Siegfried Höﬁnger1 Dipartimento di Chimica ”G. Ciamician”, Universita’ degli Studi di Bologna, Via F. Selmi 2, I-40126, Bologna, Italy sh@ciam.unibo.it http://www.ciam.unibo.it', 'ICCS_2001_146.txt': ' In-situ Bioremediation: Advantages of Parallel Computing and Graphical Investigating Techniques M.C. Baracca, G. Clai, and P. Ornelli ENEA HPCN Via Martiri di Montesole 4 40129-Bologna, ITALY email:[baracca,ornelli]@bologna.enea.it', 'ICCS_2001_147.txt': ' Can Parallel Programming Be Made Easy for Scientists? Peter Kacsuk Distinguished/Leading Professor MTA SZTAKI Research Institute H-1132 Budapest Victor Hugo 18-22. Hungary Phone: +36-(1)-329-7864 FAX: +36-(1)-329-7864 kacsuk@sztaki.hu', 'ICCS_2001_148.txt': ' A Genetic Approach for Two Dimensional Packing with Constraints Wee Sng Khoo, P. Saratchandran, and N. Sundararajan School of Electrical and Electronic Engineering, Nanyang Technological University, Singapore. Email: epsarat@ntu.edu.sg', 'ICCS_2001_149.txt': ' Phylogenetic Inference from Mitochondrial Genome Arrangement Data Donald L. Simon and Bret Larget Department of Mathematics/Computer Science Duquesne University Pittsburgh, PA 15282 {simon, larget}@mathcs.duq.edu http://www.mathcs.duq.edu/profs/{simon.html, larget.html}', 'ICCS_2001_15.txt': ' The Eﬀect of the Cusp on the Rate of Convergence of the Rayleigh-Ritz Method Ioana Sı̂rbu Harry F. King Department of Mathematics Department of Chemistry 244 Mathematics Building 330 Natural Science Complex SUNY at Buﬀalo SUNY at Buﬀalo Buﬀalo, NY 14260-2900 Buﬀalo, NY 14260', 'ICCS_2001_150.txt': ' A Comparison of Neural Networks and Classical Discriminant Analysis in Predicting Students’ Mathematics Placement Examination Scores Stephen J. Sheel1, Deborah Vrooman2, R.S. Renner 3, Shanda K. Dawsey4 1', 'ICCS_2001_152.txt': ' Towards a Coupled Environmental Prediction System', 'ICCS_2001_153.txt': ' A Spectral Element Method for Oldroyd-B Fluid in a Contraction Channel Sha Meng, Xin Kai Li, and Gwynne Evans Institute of Simulation Sciences, Faculty of Computing Science and Engineering, De Montfort University, Leicester LE1 9BH, England smeng@dmu.ac.uk, xkl@dmu.ac.uk, gaevans@dmu.ac.uk http://www.cse.dmu.ac.uk/ISS/', 'ICCS_2001_155.txt': ' Token Finding Using Mobile Agents Delbert Hart1 , Mihail E. Tudoreanu2 , and Eileen Kraemer3 1', 'ICCS_2001_156.txt': ' A Data Broker for Distributed Computing Environments 1', 'ICCS_2001_157.txt': ' Parallel Methods in Time Dependent Approaches to Reactive Scattering Calculations Valentina Piermarini1 , Leonardo Paciﬁci1 , Stefano Crocchianti1 , Antonio Laganà1 , Giuseppina D’Agosto2 , and Sergio Tasso2 1', 'ICCS_2001_158.txt': ' DeWiz - Modular Debugging for Supercomputers and Computational Grids Dieter Kranzlmüller GUP Linz, Johannes Kepler University Linz, Altenbergerstr. 69, A-4040 Linz, Austria/Europe, kranzlmueller@gup.uni-linz.ac.at, http://www.gup.uni-linz.ac.at/', 'ICCS_2001_159.txt': ' Conceptualizing a Collaborative Problem Solving Environment for Regional Climate Modeling and Assessment of Climate Impacts George Chin Jr., L. Ruby Leung, Karen Schuchardt, and Debbie Gracio Pacific Northwest National Laboratory, P.O. Box 999, Richland, Washington 99352 USA {George.Chin, Ruby.Leung, Karen.Schuchardt, Debbie.Gracio}@pnl.gov', 'ICCS_2001_16.txt': ' Strong Fault-Tolerance: Parallel Routing in Networks with Faults� Jianer Chen and Eunseuk Oh Department of Computer Science, Texas A&M University, College Station, TX 77843-3112, USA Email: {chen,eunseuko}@cs.tamu.edu', 'ICCS_2001_160.txt': ' Computational Science Education: Standards, Learning Outcomes, and Assessment Osman Yasar Department of Computational Science State University of New York Brockport, NY 14420', 'ICCS_2001_161.txt': ' Finding Steady State of Safety Systems Using the Monte Carlo Method Ray Gallagher rayg@csc.liv.ac.uk Department of Computer Science, University of Liverpool Chadwick Building, Peach Street, Liverpool, UK', 'ICCS_2001_162.txt': ' Parallel CFD Computing Using Shared Memory OpenMP Hong Hu and Edward L. Turner Department of Mathematics Hampton University, Hampton, VA 23668, USA hong.hu@hamptonu.edu', 'ICCS_2001_163.txt': ' Performance Optimization for Large Scale Computing: The Scalable VAMPIR Approach Holger Brunst1 , Manuela Winkler1 , Wolfgang E. Nagel1 , and Hans-Christian Hoppe2 1', 'ICCS_2001_164.txt': ' Computational Engineering and Science Program at the University of Utah Carleton DeTar� , Aaron L. Fogelson� , Christopher R. Johnson� , Christopher A. Sikorski� � School of', 'ICCS_2001_165.txt': ' An Area-Based Stereo Matching Using Adaptive Search Range and Window Size1 Han-Suh Koo and Chang-Sung Jeong Department of Electronics Engineering, Korea University 1-5ka, Anam-dong, Sungbuk-ku, Seoul 136-701, Korea E-mail: {esprit@snoopy, csjeong@chalie}.korea.ac.kr', 'ICCS_2001_166.txt': ' Fast Maintenance of Rectilinear Centers Sergei Bespamyatnikh1 and Michael Segal2 1', 'ICCS_2001_167.txt': ' The Simulation of Photochemical Smog Episodes in Hungary and Central Europe Using Adaptive Gridding Models István Lagzi1 , Alison S. Tomlin2 , Tamás Turányi1,3 , László Haszpra4 , Róbert Mészáros5 , and Martin Berzins6 1', 'ICCS_2001_168.txt': ' Fuzzy Logic Basis in High Performance Decision Support Systems A. Bogdanov, A. Degtyarev, and Yu. Nechaev Institute for High Performance Computing and Databases Fontanka 118, 198005 St.-Petersburg, Russia bogdanov@hm.csa.ru, deg@fn.csa.ru, int@fn.csa.ru', 'ICCS_2001_169.txt': ' Plasma Modeling of Ignition for Combustion Simulations O. Yaşar Department of Computational Science State University of New York Brockport, NY 14420 Keywords: Engine Combustion Simulations, Spark Ignition Modeling, Computational Fluid Dynamics, Plasma Properties, Equation of State Data', 'ICCS_2001_17.txt': ' Diagnosis Algorithms for a Symbolically Modeled Manufacturing Process N. Rakoto-Ravalontsalama Department of Automatic Control Ecole des Mines de Nantes 4, rue Alfred Kastler, F-44307 Nantes Cedex 03, France rakoto@auto.emn.fr', 'ICCS_2001_170.txt': ' Genetic Line Search 1', 'ICCS_2001_172.txt': ' A Precise Integration Algorithm for Matrix Riccati Differential Equations Wan-Xie Zhong1 and Jianping Zhu2 1', 'ICCS_2001_173.txt': ' Correlated, Real Time Multi-spectral Sensor Test and Evaluation (T&E) in an Installed Systems Test Facility (ISTF) Using High Performance Computing 1', 'ICCS_2001_174.txt': ' Computational Design and Performance of the Fast Ocean Atmosphere Model, Version One Robert Jacob1 , Chad Schafer2 , Ian Foster1 , Michael Tobis3 , and John Anderson3 1', 'ICCS_2001_175.txt': ' Validation Web Site: A Combustion Collaboratory over the Internet', 'ICCS_2001_176.txt': ' GEA: A Complete, Modular System for Generating Evaluative Arguments Giuseppe Carenini Department of Computer Science University of British Columbia 2366 Main Mall ,Vancouver, B.C. Canada V6T 1Z4 carenini@cs.ubc.ca', 'ICCS_2001_177.txt': ' Performance and Irregular Behavior of Adaptive Task Partitioning � Elise de Doncker, Rodger Zanny, Karlis Kaugars, and Laurentiu Cucos Department of Computer Science Western Michigan University Kalamazoo, MI 49008, USA {elise,rrzanny,kkaugars,lcucos}@cs.wmich.edu', 'ICCS_2001_178.txt': ' Producing Non-verbal Output for an Embodied Agent in an Intelligent Tutoring System 1', 'ICCS_2001_179.txt': ' Exploiting OpenMP to Provide Scalable SMP BLAS and LAPACK Routines Cliff Addison Research Manager Fujitsu European Centre for Information Technology Ltd. 2 Longwalk Road Stockley Park, Uxbridge Middlesex, England UB11 1AB Phone: +44-(208)-606-4518 FAX: +44-(208)-606-4422 addison@fecit.co.uk', 'ICCS_2001_18.txt': ' Rescheduling for Locality in Sparse Matrix Computations Michelle Mills Strout, Larry Carter, and Jeanne Ferrante University of California, San Diego', 'ICCS_2001_180.txt': ' Mapping Parallel Programs onto Distributed Computer Systems with Faulty Elements Mikhail S. Tarkov1, Youngsong Mun2, Jaeyoung Choi2, and Hyung-Il Choi2 1', 'ICCS_2001_181.txt': ' High-Performance Algorithm Engineering for Computational Phylogenetics Bernard M.E. Moret1 , David A. Bader2 , and Tandy Warnow3 1', 'ICCS_2001_182.txt': ' The Match Fit Algorithm: A Testbed for the Computational Motivation of Attention Joseph G. Billock1 , Demetri Psaltis1 , and Christof Koch1 California Institute of Technology Pasadena, CA 91125, USA billgr@sunoptics.caltech.edu', 'ICCS_2001_183.txt': ' Capacity and Capability Computing Using Legion� Anand Natrajan, Marty A. Humphrey, and Andrew S. Grimshaw Department of Computer Science, University of Virginia, Charlottesville, VA 22904', 'ICCS_2001_184.txt': ' Scientiﬁc Discovery through Advanced Computing Carl Edward Oliver Associate Director of Science for the Oﬃce of Advanced Scientiﬁc Computing Research U. S. Department of Energy, SC-30 19901 Germantown Road Germantown, Maryland 20874-1290 Phone: +1-(301)-903-7486 FAX: +1-(301)-903-4846 ed.oliver@science.doe.gov', 'ICCS_2001_185.txt': ' On the Emulation of Kohonen’s Self-Organization via Single-Map Metropolis-Hastings Algorithms Jorge Muruzábal Statistics and Decision Sc

In [ ]:
!pip install ndjson

Collecting ndjson
  Downloading ndjson-0.3.1-py2.py3-none-any.whl.metadata (3.2 kB)
Downloading ndjson-0.3.1-py2.py3-none-any.whl (5.3 kB)
Installing collected packages: ndjson
Successfully installed ndjson-0.3.1

In [ ]:
import pandas as pd
import json

with open('/content/drive/MyDrive/NIR_kurs2/data.json', 'r', encoding='utf-8') as data_file:
    data = json.load(data_file)

publications = pd.read_csv("/content/drive/MyDrive/NIR_kurs2/dataset_complete.csv", sep=';')
publications = publications['publication_name']

In [ ]:
len(data)

4409

In [ ]:
len(publications)

4523

In [ ]:
founded = {}
for el in publications:
  for key, el2 in data.items():
    if el in el2:
      print(el)
      founded[key] = el
print(len(founded))

0

In [ ]:
#Сохраняем в файл
with open('result.json', 'w', encoding='utf-8') as result_file:
    json.dump(founded, result_file, ensure_ascii=False, indent=4)

#Удаляем из data и из publications найденные статьи
for key in founded.keys():
  data.pop(key)

for el in founded.values():
  publications = publications[publications != el]

In [ ]:
from nltk.metrics import edit_distance
import re

# Функция для очистки строки
def clean_text(text):
    # Удаляем e-mail, адреса и шум
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b', '', text)  # Удаляем e-mail
    text = re.sub(r'[^\w\s]', '', text)  # Удаляем пунктуацию
    text = re.sub(r'\s+', ' ', text)  # Убираем лишние пробелы
    text = str.lower(text)
    return text.strip()

# Функция для выделения названия
def extract_core_text(file_content):
    # Берем только первые 100-150 символов (чаще название статьи в начале)
    core_text = ' '.join(file_content.split()[:20])  # Учитываем первые слова
    return clean_text(core_text)

publications1=publications
data1 = data

for el in publications1:
  el = extract_core_text(el)

for key, el2 in data1.items():
  el2 = extract_core_text(el2)

founded = {}
for key, el2 in data1.items():
  best_match = None
  best_distance = float('inf')
  for el in publications1:
    distance = edit_distance(el2, el)
    if distance < best_distance:
      best_match = el
      best_distance = distance
  print(f'{key}: {best_match}')
  founded[key] = el
  #удаляем из publications1 el
  publications1 = publications1[publications1 != best_match]
print(len(founded))

ICCS_2001_108.txt: Influences on the Solution Process for Large, Numeric-Intensive Automotive Simulations
ICCS_2001_114.txt: Fast Finite Element Analysis Method Using Multiple GPUs for Crustal Deformation and its Application to Stochastic Inversion Analysis with Geometry Uncertainty
ICCS_2001_116.txt: Large-Scale Simulation and Visualization in Medicine: Applications to Cardiology, Neuroscience, and MedicaL Imaging
ICCS_2001_123.txt: Analysis of the Argumentative Effect of Evaluative Semantics in Natural Language
ICCS_2001_127.txt: Fiddle: A Flexible Distributed Debugger Architecture
ICCS_2001_129.txt: Modeling the Effect of Premium Changes on Motor Insurance Customer Retention Rates Using Neural Networks
ICCS_2001_133.txt: MPI-OpenMP hybrid simulations using boundary integral equation and finite difference methods for earthquake dynamics and wave propagation: Application to the 2007 Niigata Chuetsu-Oki earthquake (Mw6.6)
ICCS_2001_137.txt: Corrigendum to An Empirical Evaluation of a Programming Model for Context-Dependent Real-time Streaming Applications: Procedia Computer Science, Volume 51, 2015, Pages 1423–1432
ICCS_2001_15.txt: The Effect of the Cusp on the Rate of Convergence of the Rayleigh-Ritz Method
ICCS_2001_175.txt: The Validation Web Site: A Combustion Collaboratory over the Internet
ICCS_2001_181.txt: High-Performance Algorithmic Engineering for Computationa Phylogenetics
ICCS_2001_182.txt: The Match Fit Algorithm - A Testbed for Computational Motivation of Attention
ICCS_2001_184.txt: Enabling Interoperation of High Performance, Scientific Computing Applications: Modeling Scientific Data with the Sets and Fields (SAF) Modeling System
ICCS_2001_214.txt: Cluster Configuration Aided by Simulation
ICCS_2001_215.txt: Identification and Visualization of Dominant Patterns and Anomalies in Remotely Sensed Vegetation Phenology Using a Parallel Tool for Principal Components Analysis
ICCS_2001_220.txt: Learning Computational Methods for Partial Differential Equations from the Web
ICCS_2001_221.txt: New On-line Algorithms for Modelling, Identification and Simulation of Dynamic Systems Using Modulating Functions and Non-asymptotic State Estimators: Case Study for a Chosen Physical Process
ICCS_2001_23.txt: Advancing Computational Science, Visualization and Homeland Security Research/ Education at Minority Serving Institutions National Model Promoted/ Implemented by MSI-CIEC (Minority Serving Institutions-CyberInfrastructure Empowerment Coalition)
ICCS_2001_230.txt: Peculiarities of Computer Simulation and Statistical Representation of Time—Spatial Metocean Fields
ICCS_2001_233.txt: Modelling the Runtime of the Gaussian Computational Chemistry Application and Assessing the Impacts of Microarchitectural Variations
ICCS_2001_243.txt: Cache-Efficient Multigrid Algorithms
ICCS_2001_29.txt: An Information Model for the Representation of Multiple Biological Classifications
ICCS_2001_35.txt: On Efficient Application of Implicit Runge-Kutta Methods to Large-Scale Systems of Index 1 Differential-Algebraic Equations
ICCS_2001_38.txt: The Multi-core Optimization of the Unbalanced Calculation in the Clean Numerical Simulation of Rayleigh-Bénard Turbulence
ICCS_2001_41.txt: On the Efficiency of Nearest Neighbor Searching with Data Clustered in Lower Dimensions
ICCS_2001_65.txt: On the Predictability of Rainfall in Kerala - An Application of ABF Neural Network
ICCS_2001_66.txt: HARPIC, an Hybrid Architecture Based on Representations, Perceptions, and Intelligent Control: A Way to Provide Autonomy to Robots
ICCS_2001_72.txt: An Efficient Algorithm to Calculate the Minkowski Sum of Convex 3D Polyhedra
ICCS_2001_75.txt: Preface for the Joint Workshop on Tools for Program Development and Analysis in Computational Science and Software Engineering for Large-Scale Computing
ICCS_2001_80.txt: Efficient Random Process Generation for Reliable Simulation of Complex Systems
ICCS_2001_91.txt: An Adaptive Neuro-Fuzzy Approach for Modeling and Control of Nonlinear Systems
ICCS_2001_97.txt: Performance comparison of designated preprocessing white light interferometry algorithms on emerging multi- and many-core architectures
ICCS_2002_100.txt: VORPAL as a Tool for the Study of Laser Pulse Propagation in LWFA
ICCS_2002_102.txt: OSIRIS: A Three-Dimensional, Fully Relativistic Particle in Cell Code for Modeling Plasma Based Accelerators
ICCS_2002_104.txt: Simulation of Gender Artificial Society: Multi-agent Models of Subject-Object Interactions
ICCS_2002_105.txt: Generic Large Scale 3D Visualization of Accelerators and Beam Lines
ICCS_2002_106.txt: Tracking Particles In Accelerator Optics With Crystal Elements
ICCS_2002_107.txt: Precision Dynamic Aperture Tracking in Rings
ICCS_2002_108.txt: Numerical Simulation of Hydro- and Magnetohydrodynamic Processes in the Muon Collider Target
ICCS_2002_109.txt: Superconducting RF Accelerating Cavity Developments
ICCS_2002_11.txt: The Valuation of CCIRS with a New Design
ICCS_2002_110.txt: CEA Saclay Codes Review for High Intensities Linacs Computations
ICCS_2002_111.txt: Diagonalization of Time Varying Symmetric Matrices
ICCS_2002_112.txt: One Class of Splitting Iterative Schemes
ICCS_2002_114.txt: Conservation Properties of Symmetric BVMs Applied to Linear Hamiltonian Problems

KeyboardInterrupt:

Проходимся по файлам, берем первые 200 символов. Составляем в файл. Далее смотрим каждый текст из файла и ищем вхождения.

In [ ]:
import os

files_dict = {}

directory_path = '/content/drive/MyDrive/NIR_kurs2/ICCS_files/ICCS_files'

for filename in os.listdir(directory_path):
    if filename.endswith('.txt'):
        file_path = os.path.join(directory_path, filename)
        try:
            with open(file_path, 'r', encoding='utf-8') as file:
                first_200_chars = file.read(200)
                files_dict[filename] = first_200_chars
        except Exception as e:
            print(f"Ошибка при обработке файла {filename}: {e}")

files_dict['ICCS_2021_298.txt']

'Available online at www.sciencedirect.com\n\nProcedia Computer Science 00 (2009) 000–000\n\nProcedia Computer Science 1 (2012) 2469–2478\n\nProcedia\nComputer\nScience\nwww.elsevier.com/locate/procedia\n\nwww.el'

In [ ]:
import os

files_dict = {}

directory_path = '/content/drive/MyDrive/NIR_kurs2/ICCS_files/ICCS_files'

with open('files_list.json', 'r') as file:
    files_list = json.load(file)

for filename in os.listdir(directory_path):
  if filename in files_list and filename.endswith('.txt'):
    file_path = os.path.join(directory_path, filename)
    with open(file_path, 'r', encoding='utf-8') as file:
      first_200_chars = file.read(1000)
      files_dict[filename] = first_200_chars

In [ ]:
files_dict['ICCS_2021_298.txt']

'Introducing Uncertainty Into Explanaible AI Methods\n\nSzymon Bobek1[0000−0002−6350−8405] and Grzegorz J. Nalepa1[0000−0002−8182−4225]\n\nJagiellonian Human-Centered Artiﬁcial Intelligence Laboratory (JAHCAI) and Institute of\nApplied Computer Science, Jagiellonian University, 31-007 Kraków, Poland\n{szymon.bobek,grzegorz.j.nalepa}@uj.edu.pl\n\nAbstract. Learning from uncertain or incomplete data is one of the major chal-\nlenges in building artiﬁcial intelligence systems. However, the research in this\narea is more focused on the impact of uncertainty on the algorithms performance\nor robustness, rather than on human understanding of the model and the explain-\nability of the system. In this paper we present our work in the ﬁeld of knowledge\ndiscovery from uncertain data and show its potential usage for the purpose of\nimproving system interpretability by generating Local Uncertain Explanations\n(LUX) for machine learning models. We present a method that allows to propagate\nuncertainty of data into'

In [ ]:
import json

with open('files_text.json', 'w', encoding='utf-8') as result_file:
    json.dump(files_dict, result_file, ensure_ascii=False, indent=4)

In [ ]:
for key, el in files_dict.items():
  #в нижний регистр каждую строку
  files_dict[key] = el.lower()

In [ ]:
import json

with open('files_text.json', 'r', encoding='utf-8') as result_file:
    files_dict = json.load(result_file)

За 2003 год нет данных

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/NIR_kurs2/dataset_complete.csv', sep=';', encoding='utf-8')
df = df['publication_name']
df = df.str.lower()

target = df[df.str.contains('symbolic calculation for f')]
target

2950    symbolic calculation for frölicher-nijenhuis \...
Name: publication_name, dtype: object

In [ ]:
df[2950]

'symbolic calculation for frölicher-nijenhuis \\(\\mathbb r \\)-algebra for exploring in electromagnetic field theory'

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/NIR_kurs2/dataset_complete.csv', sep=';', encoding = 'latin-1')
df = df['publication_name']

#Переводим все в нижний регистр
df = df.str.lower()

result = {}
for el in df:
  for key, el2 in files_dict.items():
    if el in el2:
      result[key] = el

print(len(result))

8

In [ ]:
with open('result.json', 'a', encoding='utf-8') as result_file:
    json.dump(result, result_file, ensure_ascii=False, indent=4)

In [ ]:
#Убрать из files_dict те строки которые есть в result по ключу

for key in result.keys():
  files_dict.pop(key)

In [ ]:
files_dict['ICCS_2021_215.txt']

KeyError: 'ICCS_2021_215.txt'

In [ ]:
import json

with open('result1.json', 'r', encoding='latin-1') as result_file:
    results = json.load(result_file)

for key, el in results.items():
  #в нижний регистр каждую строку
  results[key] = el.lower()

len(results)

5866

In [ ]:
# найти те строки в dataset_complete которых нет в result
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/NIR_kurs2/dataset_complete.csv', sep=';', encoding = 'latin-1')
df = df['publication_name'].apply(lambda x: x.lower())

unmatched = []
for el1 in df:
  if el1 not in results.values():
    unmatched.append(el1)

unmatched

['optimizing the efficiency, vulnerability and robustness of road-based para-transit networks using genetic algorithm',
 'on the configuration of robust static parallel portfolios for efficient plan generation',
 'sdf-net: real-time rigid object tracking using a deep signed distance network',
 'detecting wildlife in unmanned aerial systems imagery using convolutional neural networks trained with an automated feedback loop',
 'incentive mechanism for cooperative intrusion detection: an evolutionary game approach',
 'hybrid genetic algorithm for an on-demand first mile transit system using electric vehicles',
 'data allocation based on evolutionary data popularity clustering',
 'an innovative heuristic for planning-based urban traffic control',
 'you have more abbreviations than you know: a study of abbrevsquatting abuse',
 'parallel data-driven modeling of information spread in social networks',
 'topological street-network characterization through feature-vector and cluster analysis',
 'a distance-based tool-set to track inconsistent urban structures through complex-networks',
 'retweet prediction using social-aware probabilistic matrix factorization',
 'cascading failure based on load redistribution of a smart grid with different coupling modes',
 'measuring social responsiveness for improved handling of extreme situations',
 'a computational model-based framework to plan clinical experiments â\x80\x93 an application to vascular adaptation biology',
 'spiral wave drift induced by high-frequency forcing. parallel simulation in the luoâ\x80\x93rudy anisotropic model of cardiac tissue',
 'understanding malaria induced red blood cell deformation using data-driven lattice boltzmann simulations',
 'towards model-based policy elaboration on city scale using game theory: application to ambulance dispatching',
 'elucidation of mechanism for reducing porosity in electric arc spraying through cfd',
 'high performance computational hydrodynamic simulations: upc parallel architecture as a future alternative',
 'parallel solutions to the k-difference primer problem',
 'rt-dbscan: real-time parallel clustering of spatio-temporal data using spark-streaming',
 'gpu-based implementation of ptycho-admm for high performance x-ray imaging',
 'blockchain-based transaction integrity in distributed big data marketplace',
 'the design of fast and energy-efficient linear solvers: on the potential of half-precision arithmetic and iterative refinement techniques',
 'an experimental assessment of three point-insertion sequences for 3-d incremental delaunay tessellations',
 'the t-modified self-shrinking generator',
 'simulating negotiation-based cloud markets',
 'development of scalable three-dimensional elasto-plastic nonlinear wave propagation analysis method for earthquake damage estimation of soft grounds',
 'a new matrix-free approach for large-scale geodynamic simulations and its performance',
 'viscoelastic crustal deformation computation method with reduced random memory accesses for gpu-based computers',
 'an event detection framework for virtual observation system: anomaly identification for an acme land simulation',
 'enabling adaptive mesh refinement for single components in echam6',
 'hybrid swarm and agent-based evolutionary optimization',
 'data-driven agent-based simulation for pedestrian capacity analysis',
 'a novel agent-based modeling approach for image coding and lossless compression based on the wolf-sheep predation model',
 'an algorithm for tensor product approximation of three-dimensional material data for implicit dynamics simulations',
 'a graph-based algorithm for supervised image classification',
 'an adversarial training framework for relation classification',
 'standardization of featureless variables for machine learning models using natural language processing',
 'generalized variable conversion using k-means clustering and web scraping',
 'improving search through a3c reinforcement learning based conversational agent',
 'automatic mapping for opencl-programs on cpu/gpu heterogeneous platforms',
 'ct medical imaging reconstruction using direct algebraic methods with few projections',
 'on blood viscosity and its correlation with biological parameters',
 '1,000x faster than plink: genome-wide epistasis detection with logistic regression using combined fpga and gpu accelerators',
 'an effective model between mobile phone usage and p2p default behavior',
 'a novel data mining approach towards human resource performance appraisal',
 'a hybrid optimization algorithm for electric motor design',
 'dynamic current distribution in the electrodes of submerged arc furnace using scalar and vector potentials',
 'optimising deep learning by hyper-heuristic approach for classifying good quality images',
 'an agent-based distributed approach for bike sharing systems',
 'solving css-sprite packing problem using a transformation to the probabilistic non-oriented bin packing problem',
 'anomalous trajectory detection between regions of interest based on anpr system',
 'dynamic real-time infrastructure planning and deployment for disaster early warning systems',
 'calibration and monitoring of iot devices by means of embedded scientific visualization tools',
 'enabling machine learning on resource constrained devices by source code generation of the learned models',
 'fast retrieval of weather analogues in a multi-petabytes archive using wavelet-based fingerprints',
 'assimilation of fire perimeters and satellite detections by minimization of the residual in a fire spread model',
 'analyzing complex models using data and statistics',
 'research on technology foresight method based on intelligent convergence in open network environment',
 'bisections-weighted-by-element-size-and-order algorithm to optimize direct solver performance on 3d hp-adaptive grids',
 'the solution of the lambda modes problem using block iterative eigensolvers',
 'a versatile hybrid agent-based, particle and partial differential equations method to analyze vascular adaptation',
 'development of a multiscale simulation approach for forced migration',
 'ale method for a rotating structure immersed in the fluid and its application to the artificial heart pump in hemodynamics',
 'circular function-based gas-kinetic scheme for simulation of viscous compressible flows',
 'a new edge stabilization method for the convection-dominated diffusion-convection equations',
 'symmetric sweeping algorithms for overlaps of quadrilateral meshes of the same connectivity',
 'a two-field finite element solver for poroelasticity on quadrilateral meshes',
 'preprocessing parallelization for the alt-algorithm',
 'efficient linearly and unconditionally energy stable schemes for the phase field model of solid-state dewetting problems',
 'study on numerical methods for gas flow simulation using double-porosity double-permeability model',
 'study on topology-based identification of sources of vulnerability for natural gas pipeline networks',
 'les study on high reynolds turbulent drag-reducing flow of viscoelastic fluids based on multiple relaxation times constitutive model and mixed subgrid-scale model',
 'reducing data uncertainty in forest fire spread prediction: a matter of error function assessment',
 'analysis of the accuracy of openfoam solvers for the problem of supersonic flow around a cone',
 'modification of interval arithmetic for modelling and solving uncertainly defined problems by interval parametric integral equations system',
 'a human-inspired model to represent uncertain knowledge in the semantic web',
 'bayesian based approach learning for outcome prediction of soccer matches',
 'efficient characterization of hidden processor memory hierarchies',
 'mathematical modelling of wormhole-routed x-folded tm topology in the presence of uniform traffic',
 'adaptive time-splitting scheme for nanoparticles transport with two-phase flow in heterogeneous porous media',
 'guiding the optimization of parallel codes on multicores using an analytical cache model',
 'a modified bandwidth reduction heuristic based on the wbra and george-liu algorithm',
 'improving large-scale fingerprint-based queries in distributed infrastructure',
 'a effective truth discovery algorithm with multi-source sparse data',
 'benchmarking parallel chess search in stockfish on intel xeon and intel xeon phi processors',
 'e-zone: a faster neighbor point query algorithm for matching spacial objects',
 'application of algorithmic differentiation for exact jacobians to the universal laminar flame solver',
 'morph resolution based on autoencoders combined with effective context information',
 'old habits die hard: fingerprinting websites on the cloud',
 'service-oriented approach for internet of things',
 'the valuation of ccirs with a new design',
 'study on an n-parallel fene-p constitutive model based on multiple relaxation times for viscoelastic fluid',
 'radic based fault tolerance system with dynamic resource controller',
 'agile tuning method in successive steps for a river flow simulator',
 'how is the forged certificates in the wild: practice on large-scale ssl usage measurement and analysis',
 'managing cloud data centers with three-state server model under job abandonment phenomenon',
 'the analysis of the effectiveness of the perspective-based observational tunnels method by the example of the evaluation of possibilities to divide the multidimensional space of coal samples',
 'control driven lighting design for large-scale installations',
 'data-aware scheduling of scientific workflows in hybrid clouds',
 'large margin proximal non-parallel support vector classifiers',
 'es-gp: an effective evolutionary regression framework with gaussian process and adaptive segmentation strategy',
 'evaluating dynamic scheduling of tasks in mobile architectures using parallelme framework',
 'time series cluster analysis on electricity consumption of north hebei province in china',
 'a novel parsing-based automatic domain terminology extraction method',
 'identifying the propagation sources of stealth worms',
 'evolutionary ensemble approach for behavioral credit scoring',
 'detecting influential users in customer-oriented online communities',
 'precedent-based approach for the identification of deviant behavior in social media',
 'efficient computation of sparse higher derivative tensors',
 'rational approximation of scientific data',
 'high performance partial coherent x-ray ptychography',
 'optimization of demodulation for airâ\x80\x93gap data transmission based on backlight modulation of screen',
 'reinsertion algorithm based on destroy and repair operators for dynamic dial a ride problems',
 'optimization heuristics for computing the voronoi skeleton',
 'accurately simulating energy consumption of i/o-intensive scientific workflows',
 'analysis of the construction of similarity matrices on multi-core and many-core platforms using different similarity metrics',
 'comparing domain decomposition methods for the parallelization of distributed land surface models',
 'xscan: an integrated tool for understanding open source community-based scientific code',
 'an on-line performance introspection framework for task-based runtime systems',
 'productivity-aware design and implementation of distributed tree-based search algorithms',
 'a high-productivity framework for adaptive mesh refinement on multiple gpus',
 'how to compose product pages to enhance the new usersâ\x80\x99 interest in the item catalog?',
 'rumor detection on social media: a multi-view model using self-attention mechanism',
 'creating training data for scientific named entity recognition with minimal human effort',
 'evaluating the benefits of key-value databases for scientific applications',
 'immersed boundary method halo exchange in a hemodynamics application',
 'future ramifications of age-dependent immunity levels for measles: explorations in an individual-based model',
 'computational design of superhelices by local change of the intrinsic curvature',
 'spatial modeling of influenza outbreaks in saint petersburg using synthetic populations',
 'an agent-based model for evaluating the boarding and alighting efficiency of autonomous public transport vehicles',
 'mlp-ia: multi-label user profile based on implicit association labels',
 'estimating agriculture nir images from aerial rgb data',
 'a k-cover model for reliability-aware controller placement in software-defined networks',
 'synthesizing quantum circuits via numerical optimization',
 'application of continuous time quantum walks to image segmentation',
 'multi-source manifold outlier detection',
 'a fast knn-based approach for time sensitive anomaly detection over data streams',
 'machine learning for performance enhancement of molecular dynamics simulations',
 '2d-convolution based feature fusion for cross-modal correlation learning',
 'dundi: improving robustness of neural networks using distance metric learning',
 'autism screening using deep embedding representation',
 'function and pattern extrapolation with product-unit networks',
 'mention recommendation with context-aware probabilistic matrix factorization',
 'synchronization under control in complex networks for a panic model',
 'meshtrust: a cdn-centric trust model for reputation management on video traffic',
 'a fast 3d finite-element solver for large-scale seismic soil liquefaction analysis',
 'heuristic optimization with cpu-gpu heterogeneous wave computing for estimating three-dimensional inner structure',
 'a generic interface for godunov-type finite volume methods on adaptive triangular meshes',
 'distributed memory parallel implementation of agent-based economic models',
 'augmenting multi-agent negotiation in interconnected freight transport using complex networks analysis',
 'security-aware distributed job scheduling in cloud computing systems: a game-theoretic cellular automata-based approach',
 'residual minimization for isogeometric analysis in reduced and mixed forms',
 'ctcmodeler: an agent-based framework to simulate pathogen transmission along an inter-individual contact network in a hospital',
 'reconfiguration of the multi-channel communication system with hierarchical structure and distributed passive switching',
 'multi-agent environment for decision-support in production systems using machine learning methods',
 'meta-graph based attention-aware recommendation over heterogeneous information networks',
 'predicting heart attack through explainable artificial intelligence',
 'dynamic and distributed security management for noc based mpsocs',
 'parallelization of an algorithm for automatic classification of medical data',
 'comparing deep and machine learning approaches in bioinformatics: a mirna-target prediction case study',
 'automated epileptic seizure detection method based on the multi-attribute eeg feature pool and mrmr feature selection method',
 'a knowledge based self-adaptive differential evolution algorithm for protein structure prediction',
 'a multi-objective swarm-based algorithm for the prediction of protein structures',
 'a cloud architecture for the execution of medical imaging biomarkers',
 'a self-adaptive local search coordination in multimeme memetic algorithm for molecular docking',
 'parallel ct reconstruction for multiple slices studies with suitesparseqr factorization package',
 'arff data source library for distributed single/multiple instance, single/multiple output learning on apache spark',
 'on the role of cost-sensitive learning in imbalanced data oversampling',
 'missing features reconstruction and its impact on classification accuracy',
 'a novel distribution analysis for smote oversampling method in handling class imbalance',
 'forecasting purchase categories by transactional data: a comparative study of classification methods',
 'recognizing faults in software related difficult data',
 'factor integration based on neural networks for factor investing',
 'a brief survey of relation extraction based on distant supervision',
 'portfolio selection based on hierarchical clustering and inverse-variance weighting',
 'a computational technique for asian option pricing model',
 'improving portfolio optimization using weighted link prediction in dynamic stock networks',
 'dynamic partitioning of evolving graph streams using nature-inspired heuristics',
 'fully-asynchronous cache-efficient simulation of detailed neural networks',
 'application of the model with a non-gaussian linear scalar filters to determine life expectancy, taking into account the cause of death',
 'improving ode integration on graphics processing units by reducing thread divergence',
 'an algorithm for hydraulic tomography based on a mixture model',
 'rapid multi-band patch antenna yield estimation using polynomial chaos-kriging',
 'an algorithm for selecting measurements with high information content regarding parameter identification',
 'optimizing parallel performance of the cell based blood flow simulation software hemocell',
 'surrogate-based optimization of tidal turbine arrays: a case study for the faro-olhã£o inlet',
 'evaluation of the suitability of intel xeon phi clusters for the simulation of ultrasound wave propagation using pseudospectral methods',
 'fog computing architecture based blockchain for industrial iot',
 'exploration of data from smart bands in the cloud and on the edge â\x80\x93 the impact on the data storage space',
 'fogflow - computation organization for heterogeneous fog computing environments',
 'noise mapping through mobile crowdsourcing for enhanced living environments',
 'environmental quality supervision for enhanced living environments and laboratory activity support using ibm watson internet of things platform',
 'computationally efficient classification of audio events using binary masked cochleagrams',
 'efficient parallel associative classification based on rules memoization',
 'anomaly detection in social media using recurrent neural network',
 'an innovative and reliable water leak detection service supported by data-intensive remote sensing processing',
 'kernel embedded nonlinear observational mappings in the variational mapping particle filter',
 'data assimilation in a nonlinear time-delayed dynamical system with lagrangian optimization',
 'machine learning to approximate solutions of ordinary differential equations: neural networks vs. linear regressors',
 'tuning covariance localization using machine learning',
 'marine and atmospheric forecast computational system for nautical sports in guanabara bay (brazil)',
 'climate evaluation of a high-resolution regional model over the canary current upwelling system',
 'validating ocean general circulation models via lagrangian particle simulation and data from drifting buoys',
 'numerical characterization of the douro river plume',
 'estuarine light attenuation modelling towards improved management of coastal fisheries',
 'the narval software toolbox in support of ocean models skill assessment at regional and coastal scales',
 'salinity control on saigon river downstream of dautieng reservoir within multi-objective simulation-optimisation framework for reservoir operation',
 'early warning systems for shellfish safety: the pivotal role of computational science',
 'creating a reusable cross-disciplinary multi-scale and multi-physics framework: from amuse to omuse and beyond',
 'mamico: parallel noise reduction for multi-instance molecular-continuum flow simulation',
 'introducing vecmatk - verification, validation and uncertainty quantification for multiscale and hpc simulations',
 'effects of numerical integration on dlm/fd method for solving interface problems with body-unfitted meshes',
 'a bubble formation in the two-phase system',
 'dns of mass transfer from bubbles rising in a vertical channel',
 'a hybrid vortex method for the simulation of 3d incompressible flows',

In [ ]:
len(unmatched)

1934

In [ ]:
#сохранить unmatched в файл
with open('files_text1.json', 'r', encoding='latin-1') as result_file:
    data = json.load(result_file)

keys = list(data.keys())

with open('files_unmatched.json', 'w', encoding='utf-8') as result_file:
    json.dump(keys, result_file, ensure_ascii=False, indent=4)